### ISSUE TITLE
Value for Context description stays in "create context" form

### ISSUE THREAD

**Issue by hofmannc** [MPDL/PubManAdmin#8]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 26.10.2017
User: roland

Action:
log in roland -> start page -> context-> "+" -> enter context name -> enter context description -> select ou -> save
context correctly displayed
-> context -> "+" -> 

Observation: the description I entered for the first context is still displayed in form for new context
same observation for OU -> "name" / "adress"

**Comment by wilhelmfrank** [comment]
FIXED! created new Context class to replace const.

**Comment by hofmannc** [comment]
Testserver:
https://dev.inge.mpdl.mpg.de/admintool/users
Browser: ff
Version/test date: 04.12.2017
User: roland

test result:
ok for contexts
NOK: still reproducible for OU

**Comment by wilhelmfrank** [comment]
FIXED! created new OU class to replace const.

**Comment by hofmannc** [comment]
Testserver: qa.inge.mpdl.mpg.de/admintool/
Browser: Firefox 59.0.2 (64-Bit)
Tested version: 1.0.6
Test date: 19.07.2018
User: roland
result: ok
